### ISSUE TITLE
[BUG] vm_builder.py error message

### ISSUE THREAD

**Issue by mawah** [microsoft/computervision-recipes#391]
### Description

Cloned the repo locally (Windows laptop) and tried to run `python contrib/vm_builder/vm_builder.py` per setup directions. Got the below output:

```
Pricing information on the SKUs can be found here:
https://azure.microsoft.com/en-us/pricing/details/virtual-machines

To use this utility, you must have an Azure subscription which you can
get from azure.microsoft.com.

Answer the questions below to setup your machine.

------------------------------------------

Press enter to continue... [I pressed enter]

Checking to see if you are logged in...
Traceback (most recent call last):
  File "contrib/vm_builder/vm_builder.py", line 624, in <module>
    vm_builder()
  File "contrib/vm_builder/vm_builder.py", line 582, in vm_builder
    logged_in = check_logged_in()
  File "contrib/vm_builder/vm_builder.py", line 384, in check_logged_in
    stderr=subprocess.PIPE,
  File "C:\Anaconda3\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### In which platform does it happen?

My Windows laptop with azure cli and bash extension installed

### How do we replicate the issue?

See above in description

### Expected behavior (i.e. solution)

No error message and ability to provision VM.

**Comment by jiata** [comment]
right, i think this tool only works on Linux. I'll add a note about that.

**Comment by PatrickBue** [comment]
@jiata Can we close this?
