### ISSUE TITLE
[BUG] Error occurred: User program failed with TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by konabuta** [microsoft/computervision-recipes#462]
### Description

detection/11_exploring_hyperparameters_on_azureml.ipynb failed with error

### In which platform does it happen?

Azure Machine Learning Hyperdrive

Ubuntu (Machine Learning Compute)

GPU  (STANDARD_NC6S_V3)

Client : Azure ML Notebook VM

### How do we replicate the issue?

Run this notebook on Azure ML Python SDK 1.0.81. I confirmed that it also has same issue on Python SDK 1.0.76.

 

This is error log.

```
The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.0006413459777832031 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 138
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    detector.fit(params["epochs"], lr=params["learning_rate"], print_freq=1)
  File "/mnt/batch/tasks/shared/LS_root/jobs/azureml-ws/azureml/hyperparameter-tuning_1577330821126235_1/mounts/workspaceblobstore/azureml/hyperparameter-tuning_1577330821126235_1/utils_cv/detection/model.py", line 525, in fit
    e = self.evaluate(dl=self.dataset.test_dl)
  File "/mnt/batch/tasks/shared/LS_root/jobs/azureml-ws/azureml/hyperparameter-tuning_1577330821126235_1/mounts/workspaceblobstore/azureml/hyperparameter-tuning_1577330821126235_1/utils_cv/detection/model.py", line 564, in evaluate
    self.results = evaluate(self.model, dl, device=self.device)
  File "/azureml-envs/azureml_d0591d598c843da5424078d2e7ba6755/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/jobs/azureml-ws/azureml/hyperparameter-tuning_1577330821126235_1/mounts/workspaceblobstore/azureml/hyperparameter-tuning_1577330821126235_1/utils_cv/detection/references/engine.py", line 90, in evaluate
    coco_evaluator = CocoEvaluator(coco, iou_types)
  File "/mnt/batch/tasks/shared/LS_root/jobs/azureml-ws/azureml/hyperparameter-tuning_1577330821126235_1/mounts/workspaceblobstore/azureml/hyperparameter-tuning_1577330821126235_1/utils_cv/detection/references/coco_eval.py", line 26, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "/azureml-envs/azureml_d0591d598c843da5424078d2e7ba6755/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/azureml-envs/azureml_d0591d598c843da5424078d2e7ba6755/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/azureml-envs/azureml_d0591d598c843da5424078d2e7ba6755/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/azureml-envs/azureml_d0591d598c843da5424078d2e7ba6755/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

2019/12/26 03:30:59 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2019/12/26 03:30:59 MPI publisher: intel ; version: 2018

Error occurred: User program failed with TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

### Expected behavior (i.e. solution)

Run this notebook runs successfully

**Comment by ujsyehao** [comment]
you can refer to https://github.com/xingyizhou/CenterNet/issues/547

**Comment by konabuta** [comment]
@ujsyehao Thanks, it works now.

**Comment by konabuta** [comment]
Hi experts,

I want to fix this notebook to avoid this problem. Original notebook uses Azure ML Estimator that specifies pip & conda packages. I changed my code so that Estimator refers to environment.yml as conda dependencies to run on the same python environment just like local client. If it's no problem, let me make pull request.

**changed files**
- [11_exploring_hyperparameters_on_azureml.ipynb](https://github.com/konabuta/computervision-recipes/blob/konabuta/coco-api/scenarios/detection/11_exploring_hyperparameters_on_azureml.ipynb)
- [environment.yml](https://github.com/konabuta/computervision-recipes/blob/konabuta/coco-api/environment.yml)

environment.yml refers to my original cocoapi to support numpy 1.18. I just make change the following code in [cocoeval.py](https://github.com/konabuta/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py)

before (line : 507)
 `self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)`

after (line: 508)        
`self.iouThrs = np.linspace(.5, 0.95, int(np.round(0.95 - .5) / .05 + 1), endpoint=True)
`
